# Generated by Django 5.2.7 on 2025-11-01 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ride_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('driver', 'Driver'), ('rider', 'Rider'), ('admin', 'Admin')], max_length=50),
        ),
    ]
