# Generated by Django 5.2.7 on 2025-11-02 15:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ride_app', '0002_alter_user_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ride',
            name='id_driver',
            field=models.ForeignKey(db_column='id_driver', on_delete=django.db.models.deletion.CASCADE, related_name='rides_as_driver', to=settings.AUTH_USER_MODEL),
        ),
    ]
